version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
jobs:
  setup-client:
    docker:
      - image: circleci/node:10
    working_directory: ~/memento/
    steps:
      - checkout
      - attach_workspace:
          at: ~/memento/
      # Restore dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install all needed dependencies from package.json
      - run:
          name: Install React Dependencies
          command: npm i --prefix client

      # Save the cache including node_modules folder
      - save_cache:
          paths:
            - client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      - persist_to_workspace:
          root: ~/memento/client
          paths:
            - node_modules
  build-client:
    docker:
      - image: circleci/node:10
    working_directory: ~/memento/
    steps:
      - checkout
      - attach_workspace:
          at: ~/memento/client
      - run:
          working_directory: client
          name: Print Client
          command: ls -l
      # Run React build
      - run:
          name: React Build
          command: npm run build --prefix client
      - persist_to_workspace:
          root: ~/memento/client
          paths:
            - build
  # deploy:
  #   docker:
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  # deploy-client:
  #   docker:
  #     - image: circleci/node:10
  #   working_directory: ~/memento/
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: client
  #     - run:
  #         working_directory: client
  #         name: Print Client
  #         command: ls -l
  #     # Deploy React to Firebase Hosting
  #     - run:
  #         working_directory: client
  #         name: Deploy to Firebase Hosting
  #         command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
  # deploy:
  #   executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
  #   steps:
  #     - checkout
  #     - heroku/install # Runs the heroku install command, if necessary.
  #     - heroku/deploy-via-git: # Deploys branch to Heroku via git push.
  setup-backend:
    docker:
      - image: circleci/node:10
    working_directory: ~/memento/
    steps:
      - checkout
      - attach_workspace:
          at: ~/memento/
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Install all needed dependencies from package.json
      - run:
          name: Install Node JS + Express Dependencies
          command: npm i
      # Save the cache including node_modules folder
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}\
      - persist_to_workspace:
          root: ~/memento/
          paths:
            - node_modules
  test-backend:
    docker:
      - image: circleci/node:8
    working_directory: ~/memento/
    steps:
      - checkout
      - attach_workspace:
          at: ~/memento/
      # Run Jest Tests
      - run:
          name: Run Jest Tests
          command: npm run test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup-client
      - setup-backend
      - build-client:
          requires:
            - setup-client
      - test-backend
          requires:
            - setup-backend
      - heroku/deploy-via-git:
          requires:
            - build-client
